version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sessiondb
      MYSQL_USER: sessionuser
      MYSQL_PASSWORD: sessionpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  session-service:
    build: .
    container_name: session-service
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://db:3306/sessiondb?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: sessionuser
      DB_PASS: sessionpass
      command: >
        sh -c "sleep 5 && java -jar session-service.jar server config.yml --config=config.yml"

volumes:
  mysql-data:

